language: php

stages:
  - smoke test 🕵️
  - test

jobs:
  include:
    - stage: smoke test 🕵️
      php: 7.0
      env: DEPS='lowest' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[total]=413'
    -
      php: 7.4
      env: DEPS='unmodified' WITH_STATIC_ANALYSIS='yes' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=9'

    - stage: test
      php: 7.0
      env: SYMFONY_VERSION='3.4.*'
    -
      php: 7.1
      env: SYMFONY_VERSION='3.4.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=10'
    -
      php: 7.2
      env: SYMFONY_VERSION='3.4.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=10'
    -
      php: 7.3
      env: SYMFONY_VERSION='3.4.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=10'
    -
      php: 7.3
      env: SYMFONY_VERSION='4.3.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=10'
    -
      php: 7.3
      env: SYMFONY_VERSION='4.4.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=9'
    -
      php: 7.3
      env: SYMFONY_VERSION='5.0.*' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=9'
    -
      php: 7.3
      env: SYMFONY_VERSION='5.0.*' MIN_STABILITY='dev' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=9'
  allow_failures:
    - env: SYMFONY_VERSION='5.0.*' MIN_STABILITY='dev' SYMFONY_DEPRECATIONS_HELPER='max[self]=0&max[direct]=2&max[indirect]=9'
  fast_finish: true

services:
  - postgresql

install:
  # set unlimited memory_limit
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "memory_limit = -1" >> "${INI_FILE}"
  # disable Xdebug for better Composer performance
  - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi;
  # install dependencies using Composer
  - travis_wait bash .travis_install_dependencies.sh
  # show installed dependencies
  - composer show

before_script:
  # set up MySQL
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root -e 'GRANT USAGE ON *.* TO "travis"@"localhost"; DROP USER "travis"@"localhost";'
  - mysql -u root -e 'CREATE USER "travis"@"localhost" IDENTIFIED BY PASSWORD "";'
  - mysql -u root -e 'GRANT ALL ON test.* TO "travis"@"localhost"; FLUSH PRIVILEGES;'
  # set up PostgreSQL
  - psql -c 'create database test;' -U postgres

script:
  # validate composer.json
  - if [ -n "${WITH_STATIC_ANALYSIS:-}" ]; then composer validate --strict --no-check-lock; fi;
  # run PHPStan
  - if [ -n "${WITH_STATIC_ANALYSIS:-}" ]; then vendor/bin/phpstan analyse; fi;
  # run PHPUnit
  - vendor/bin/phpunit -v

services:
  - mysql
  - postgresql

notifications:
  email:
    on_success: always
    on_failure: always

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
